//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeReader.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BarcodeReader.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MainPage_LabelBarcodeCode {
            get {
                return ResourceManager.GetString("MainPage_LabelBarcodeCode", resourceCulture);
            }
        }
        
        public static string MainPage_LabelBarcodeType {
            get {
                return ResourceManager.GetString("MainPage_LabelBarcodeType", resourceCulture);
            }
        }
        
        public static string MainPage_ButtonReadBarcode {
            get {
                return ResourceManager.GetString("MainPage_ButtonReadBarcode", resourceCulture);
            }
        }
        
        public static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        public static string MainPage_EntryBarcodeType_Placeholder {
            get {
                return ResourceManager.GetString("MainPage_EntryBarcodeType_Placeholder", resourceCulture);
            }
        }
        
        public static string MainPage_EntryBarcodeValue_Placeholder {
            get {
                return ResourceManager.GetString("MainPage_EntryBarcodeValue_Placeholder", resourceCulture);
            }
        }
        
        public static string BarcodePage_Scanner_BottomText {
            get {
                return ResourceManager.GetString("BarcodePage_Scanner_BottomText", resourceCulture);
            }
        }
    }
}
